### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by Swirren** [LeafCommunity/ConcreteMixer#1]
Getting this error on my survival server, but not when I'm on a blank test server
![image](https://user-images.githubusercontent.com/64167426/207315779-c3ce27a1-e713-4477-8fbd-80d6b021a332.png)

**Comment by RezzedUp** [comment]
Thanks for the report - sorry about cluttering your console like that! Please make sure you're running the latest version of GriefPrevention (should be `16.18`).

**Comment by Swirren** [comment]
Terribly sorry, that was it. Thanks!
